# Generated by Django 6.0.5 on 2026-06-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('yearly_target_hours', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
