# Generated by Django 6.0.5 on 2026-06-02 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('entry_date', models.DateField()),
                ('etcs_authorized', models.BooleanField(default=False)),
                ('external_signal_authorized', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('employee', 'Mitarbeiter'), ('admin', 'Admin'), ('superuser', 'Superuser')], default='employee', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.category')),
            ],
        ),
    ]
