# Generated by Django 6.0.6 on 2026-08-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Mitarbeiter'), ('admin', 'Admin')], default='employee', max_length=20),
        ),
    ]
