# Generated by Django 6.0.6 on 2026-08-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='etcs_authorized',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='external_signal_authorized',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='etcs_level1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='etcs_level2',
            field=models.BooleanField(default=False),
        ),
    ]
