# Generated by Django 6.0.6 on 2026-07-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['name'], 'verbose_name': 'Betriebspunkt', 'verbose_name_plural': 'Betriebspunkte'},
        ),
        migrations.AddField(
            model_name='station',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bemerkung'),
        ),
        migrations.AddField(
            model_name='station',
            name='x',
            field=models.FloatField(blank=True, null=True, verbose_name='X-Koordinate'),
        ),
        migrations.AddField(
            model_name='station',
            name='y',
            field=models.FloatField(blank=True, null=True, verbose_name='Y-Koordinate'),
        ),
    ]
