# Generated by Django 6.0.6 on 2026-07-01 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Streckennummer')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Strecke',
                'verbose_name_plural': 'Strecken',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='strecken.route')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
            options={
                'verbose_name': 'Betriebspunkt auf Strecke',
                'verbose_name_plural': 'Betriebspunkte auf Strecken',
                'ordering': ['route', 'position'],
                'unique_together': {('route', 'position')},
            },
        ),
    ]
