# Generated by Django 6.0.6 on 2026-07-01 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_user'),
        ('strecken', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ausbildung', 'In Ausbildung'), ('kundig', 'Kundig'), ('abgelaufen', 'Abgelaufen')], default='kundig', max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('last_trip', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='employees.employee')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='strecken.route')),
            ],
            options={
                'verbose_name': 'Streckenkundigkeit',
                'verbose_name_plural': 'Streckenkundigkeiten',
                'ordering': ['employee', 'route'],
                'unique_together': {('employee', 'route')},
            },
        ),
    ]
