# Generated by Django 6.0.6 on 2026-07-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strecken', '0002_employeeroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestation',
            name='kilometer',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
    ]
