# Generated by Django 6.0.6 on 2026-06-21 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='etcs',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='service_type',
        ),
        migrations.AddField(
            model_name='trip',
            name='from_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='stations.station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='to_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='stations.station'),
            preserve_default=False,
        ),
    ]
