# Generated by Django 6.0.6 on 2026-06-30 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_trip_etcs_remove_trip_service_type_and_more'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='shunting_type',
            field=models.CharField(blank=True, choices=[('direkt', 'Direkt'), ('indirekt', 'Indirekt')], max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='traffic_type',
            field=models.CharField(choices=[('zug', 'Zug'), ('rangieren', 'Rangierbewegung')], default='zug', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='train_number',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicle'),
        ),
    ]
