# Generated by Django 6.0.6 on 2026-08-19 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('employees', '0004_alter_employee_role'),
        ('stations', '0002_alter_station_options_station_remarks_station_x_and_more'),
        ('trips', '0003_trip_shunting_type_trip_traffic_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='stations.station'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='train_number',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
