# Generated by Django 6.0.6 on 2026-08-19 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('trips', '0004_trip_user_profile_alter_trip_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='employee',
        ),
        migrations.AlterField(
            model_name='trip',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='accounts.userprofile'),
        ),
    ]
